name: Develop - Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: Delta-mesh
    environment: develop
    env:
      SERVICE_NAME: webapp.service
      SERVICE_PORT: ${{secrets.DEVELOP_PORT}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Start WebApp
      shell: bash
      run: |
        # Download and install nvm:
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

        pwd

        # in lieu of restarting the shell
        \. "$HOME/.nvm/nvm.sh"

        # Download and install Node.js:
        nvm install 22

        # Set the installed Node.js version as the default globally:
        nvm alias default 22

        # Verify the Node.js version:
        node -v # Should print "v22.15.0".
        nvm current # Should print "v22.15.0".

        # Verify npm version:
        npm -v # Should print "10.9.2".
        
        cd WebApp
        npm init -y
        npm install --legacy-peer-deps
        npm run dev -- -p $SERVICE_PORT 