name: Develop - Deployment

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
    deploy:
      runs-on: Delta-mesh
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            clean: false

        - name: Execute test_webapp.sh
          run: |
            chmod +x ./test_webapp.sh
            ./test_webapp.sh 5054

    