name: Develop - Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: Delta-mesh
    environment: develop
    env:
      SERVICE_NAME: webapp.service
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Make all .sh files executable
      run: find . -name "*.sh" -exec chmod +x {} \;

    - name: Create log directory
      run: |
        echo ${{ secrets.ROOT_PASSWORD }} | sudo -S mkdir -p /var/log/webapp
        echo ${{ secrets.ROOT_PASSWORD }} | sudo -S chown $(whoami) /var/log/webapp

    - name: Create or update systemd service file
      run: |
        echo "[Unit]
        Description=Web App Service
        After=network.target

        [Service]
        ExecStart=$(pwd)/test_webapp.sh ${{ secrets.DEVELOP_PORT }} >> /var/log/webapp/output.log 2>&1
        Restart=on-failure
        User=$(whoami)
        WorkingDirectory=$(pwd)

        [Install]
        WantedBy=multi-user.target" | sudo -S tee /etc/systemd/system/$SERVICE_NAME <<< ${{ secrets.ROOT_PASSWORD }}

    - name: Configure log rotation
      run: |
        echo "/var/log/webapp/*.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          copytruncate
        }" | echo ${{ secrets.ROOT_PASSWORD }} | sudo -S tee /etc/logrotate.d/webapp

    - name: Reload systemd and restart service
      run: |
        echo ${{ secrets.ROOT_PASSWORD }} | sudo -S systemctl daemon-reload
        echo ${{ secrets.ROOT_PASSWORD }} | sudo -S systemctl stop $SERVICE_NAME || echo "Service not running"
        echo ${{ secrets.ROOT_PASSWORD }} | sudo -S systemctl start $SERVICE_NAME
        echo ${{ secrets.ROOT_PASSWORD }} | sudo -S systemctl enable $SERVICE_NAME
