name: Develop - Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: Delta-mesh
    environment: develop
    env:
      SERVICE_NAME: webapp.service
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Make all .sh files executable
      run: find . -name "*.sh" -exec chmod +x {} \;

    - name: Create log directory
      run: |
        sudo mkdir -p /var/log/webapp
        sudo chown $(whoami) /var/log/webapp

    - name: Create or update systemd service file
      run: |
        echo "[Unit]
        Description=Web App Service
        After=network.target

        [Service]
        ExecStart=$(pwd)/test_webapp.sh ${{ secrets.DEVELOP_PORT }} >> /var/log/webapp/output.log 2>&1
        Restart=on-failure
        User=$(whoami)
        WorkingDirectory=$(pwd)

        [Install]
        WantedBy=multi-user.target" | sudo tee /etc/systemd/system/$SERVICE_NAME

    - name: Configure log rotation
      run: |
        echo "/var/log/webapp/*.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          copytruncate
        }" | sudo tee /etc/logrotate.d/webapp

    - name: Reload systemd and restart service
      run: |
        sudo systemctl daemon-reload
        sudo systemctl stop $SERVICE_NAME || echo "Service not running"
        sudo systemctl start $SERVICE_NAME
        sudo systemctl enable $SERVICE_NAME

    # - name: Tail logs until script completes
    #   run: |
    #     echo "Waiting for service to complete..."
    #     while sudo systemctl is-active --quiet $SERVICE_NAME; do
    #       sudo tail -n 20 /var/log/webapp/output.log
    #       sleep 5
    #     done
    #     echo "Service execution completed."