name: Develop - Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: Delta-mesh
    environment: develop
    env:
      SERVICE_NAME: webapp.service
      SERVICE_PORT: ${{ secrets.DEVELOP_PORT }}
      REPOSITORY_CLONE_URL: ${{ secrets.REPOSITORY_CLONE_URL }}
      REPOSITORY_DIR: /home/administrator/UnityRenderStreaming/
    steps:
    - name: Set up REPOSITORY
      run: |
        if [ ! -d $REPOSITORY_DIR ]; then
          echo "Repository directory does not exist, cloning the repository."
          git clone $REPOSITORY_CLONE_URL $REPOSITORY_DIR
        fi
        cd $REPOSITORY_DIR
        git fetch origin develop
        git reset --hard origin/develop

    - name: Start WebApp
      run: |
        cd $REPOSITORY_DIR
        which node