name: Develop - Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: Delta-mesh
    environment: develop
    env:
      SERVICE_NAME: webapp.service
      SERVICE_PORT: ${{secrets.DEVELOP_PORT}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Start WebApp
      run: |
        sh ./install_npm.sh
        sh ./test_webapp.sh $SERVICE_PORT