name: Develop - Deployment

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: Delta-mesh
    env:
      RANDOM_PORT: $((RANDOM + 1024))
      PROCESS_ID_FILE: process_id.txt
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Execute test_webapp.sh with random port
      run: |
        echo "Using random port: $RANDOM_PORT"
        sudo chmod +x ./test_webapp.sh
        ./test_webapp.sh --port $RANDOM_PORT &
        echo $! > $PROCESS_ID_FILE

    - name: Kill test_webapp.sh process
      if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        if [ -f $PROCESS_ID_FILE ]; then
          kill $(cat $PROCESS_ID_FILE) || echo "Process already terminated"
          rm $PROCESS_ID_FILE
        fi