name: Develop - Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: Delta-mesh
    environment: develop
    env:
      SERVICE_NAME: webapp_develop.service
      RUN_FILE: run_develop.sh
      REPOSITORY_CLONE_URL: ${{ secrets.REPOSITORY_CLONE_URL }}
      REPOSITORY_DIR: /home/administrator/UnityRenderStreaming
    steps:

    - name: Connect to Server
      shell: bash
      run: |
        ls
        if [ ! -d $REPOSITORY_DIR ]; then
          echo "Repository directory does not exist, cloning the repository."
          git clone $REPOSITORY_CLONE_URL $REPOSITORY_DIR
        fi
        cd $REPOSITORY_DIR
        git fetch origin develop
        git reset --hard origin/develop

    - name: Setup Systemd Service
      shell: bash
      run: |
        sudo chmod +x $REPOSITORY_DIR/$RUN_FILE
        sudo cp -f $REPOSITORY_DIR/$SERVICE_NAME /etc/systemd/system/$SERVICE_NAME
        sudo chmod 644 /etc/systemd/system/$SERVICE_NAME

    - name: Restart Service
      shell: bash
      run: |
        sudo systemctl daemon-reload
        sudo systemctl enable $SERVICE_NAME
        sudo systemctl stop $SERVICE_NAME
        sudo systemctl start $SERVICE_NAME
        sudo systemctl status $SERVICE_NAME