name: Prod - Deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: Delta-mesh
    environment: prod
    env:
      SERVICE_NAME: webapp_prod.service
      RUN_FILE: run_prod.sh
      REPOSITORY_CLONE_URL: ${{ secrets.REPOSITORY_CLONE_URL }}
      REPOSITORY_DIR: /home/administrator/prod/UnityRenderStreaming
    steps:

    - name: Sync Repository
      shell: bash
      run: |
        if [ ! -d $REPOSITORY_DIR ]; then
          echo "Repository directory does not exist, creating the directory."
          mkdir -p $REPOSITORY_DIR
          echo "Cloning the repository."
          git clone $REPOSITORY_CLONE_URL $REPOSITORY_DIR
        fi
        cd $REPOSITORY_DIR
        git fetch origin prod
        git reset --hard origin/prod

    - name: Setup Systemd Service
      shell: bash
      run: |
        sudo chmod +x $REPOSITORY_DIR/$RUN_FILE
        sudo cp -f $REPOSITORY_DIR/$SERVICE_NAME /etc/systemd/system/$SERVICE_NAME
        sudo chmod 644 /etc/systemd/system/$SERVICE_NAME

    - name: Restart Service
      shell: bash
      run: |
        sudo systemctl daemon-reload
        sudo systemctl enable $SERVICE_NAME
        sudo systemctl stop $SERVICE_NAME
        sudo systemctl start $SERVICE_NAME
        sudo systemctl status $SERVICE_NAME